version: '2.4'
services:
  mysql_database:
    image: mysql:8.0.33
    container_name: mysql_database
    cap_add:
      - SYS_NICE
    restart: always
    environment:
      - MYSQL_DATABASE=bookapp
      - MYSQL_ROOT_PASSWORD=root
    ports:
      - 3306:3306
    networks:
      - database_network
    volumes:
      - data:/var/lib/mysql
  glassfish:
    image: omnifish/glassfish:7.0.4
    container_name: glassfish
    restart: always
    ports:
      - 8080:8080
      - 4848:4848
    volumes:
      - ./target/book-app-1.0-SNAPSHOT.war:/opt/glassfish7/glassfish/domains/domain1/autodeploy/book-app-1.0-SNAPSHOT.war:ro
    networks:
      - database_network
    depends_on:
      - mysql_database
    links:
      - mysql_database
networks:
  database_network:
    driver: bridge
volumes:
  data:
    driver: local